### PR TITLE
check for zero receiver in transaction

### PR DESCRIPTION
**Pull request by mjiang102628**
- add unit test for zero receiver
- issue #115

### CODE REVIEW

**Review by EvanJRichard — APPROVED** [review]
It's illegal to have a zero receiver, right? If so LGTM

**Comment by EvanJRichard** [comment]
Update, it's legal at the protocol level to have a zero receiver (such as for a close-to transaction), see https://github.com/algorand/js-algorand-sdk/issues/175 . I think this change might still be useful, though, so letting approval stand.

**Review by EvanJRichard — CHANGES_REQUESTED** [review]
After speaking with @algorotem in standup, we might not want this change, or maybe we want to allow the zero receiver but only if the user-dev explicitly calls for it, or something.

**Review by EvanJRichard — APPROVED** [review]

**Review by jasonpaulos — APPROVED** [review]
Looks good, but can you add unit tests to ensure errors will be raised if the receiver is None for `PaymentTxn` and `AssetTransferTxn`?

**Comment by jasonpaulos** [comment]
LGTM 👍

**Pull request merged**
