### PR TITLE
Create dryrun

### PR DESCRIPTION
**Pull request by barnjamin**
Initial stab at providing utility function to create DryrunRequest object from transaction list given a client.

Probably needs tests but I need guidance on what tests and where they should go

### CODE REVIEW

**Comment by barnjamin** [comment]
addresses https://github.com/algorand/py-algorand-sdk/issues/258

**Comment by jasonpaulos** [comment]
This seems like a good addition. My one suggestion would be that maybe the `AtomicTransactionComposer` should have a method to generate a dryrun request as well?

**Comment by barnjamin** [comment]
> My one suggestion would be that maybe the AtomicTransactionComposer should have a method to generate a dryrun request as well

Do you mean add a method in the AtomicTransactionComposer class that creates the dryrun (and submits it?). I was thinking users may just call build then pass the result to this method.

Does it make sense to also add a method to write to a file? Essentially https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/testing/dryrun.py#L820

**Comment by jasonpaulos** [comment]
> Do you mean add a method in the AtomicTransactionComposer class that creates the dryrun (and submits it?). I was thinking users may just call build then pass the result to this method.

Yeah I was suggesting adding a method to the composer to streamline the process. I hadn't considered having the composer also submitting the dryrun request, but that seems like potentially a good idea too.
 
> Does it make sense to also add a method to write to a file? Essentially https://github.com/algorand/py-algorand-sdk/blob/develop/algosdk/testing/dryrun.py#L820

Personally I think the SDKs should _only_ provide a way to encode and decode objects to bytes for storage, not specific IO for files. The reason being it requires minimal additional code to read/write encoded bytes to files, and if we focus only on file IO we can't address any other storage mechanisms, like DBs or sending objects over the network.

**Comment by barnjamin** [comment]
> Yeah I was suggesting adding a method to the composer to streamline the process.

I'd like to add this in a separate PR if that is ok? Maybe use this method to construct it internally

**Review by jasonpaulos — APPROVED** [review]

**Pull request merged**
