### PR TITLE
Matrix test across Python versions for unit tests

### PR DESCRIPTION
**Pull request by michaeldiamant**
Follows #323 to unit test Python 3.8, 3.9, and 3.10 in order to improve confidence that changes _work_ across Python versions.

Details:
* Setting up matrix tests for integration tests is a larger scoped exercise than I budgeted.  Since the tests rely on a VM, Python customization is more involved than selecting a custom image. 
  * To avoid losing sight of the desire, I documented https://github.com/algorand/py-algorand-sdk/issues/324 - _CI: Matrix test across Python versions for integration tests_
  * I confirmed the `integration-test` machine image (`ubuntu-2004:202104-01`) runs the targeted minimum Python version (3.8) by checking https://circleci.com/docs/2.0/configuration-reference/#machine.
* Here's a CircleCI reference explaining the PR's syntax:  https://circleci.com/blog/circleci-matrix-jobs/.

### CODE REVIEW

**Review by winder — APPROVED** [review]

**Review by algochoi — COMMENTED** [review]
Should the matrix also test the `docset`?

**Review by tzaffi — APPROVED** [review]
LGTM

**Comment by michaeldiamant** [comment]
> Should the matrix also test the docset?

@algochoi I left `docset` as is because I _assumed_ library consumers do _not_ generate docs.  Is it a fair assumption?

**Comment by algochoi** [comment]
> > Should the matrix also test the docset?
> 
> @algochoi I left `docset` as is because I _assumed_ library consumers do _not_ generate docs. Is it a fair assumption?

The assumption sounds okay to me - sometimes I build the docs locally, but I don't really see it as a blocker or whether it would affect this.

**Review by algochoi — APPROVED** [review]

**Comment by jasonpaulos** [comment]
This looks good as is, but extra effort is needed to make cucumber tests run with the appropriate Python version. Currently our `Dockerfile` runs all cucumber tests in Python 3.7.9.

A while ago I made this PR to the Go SDK to achieve the same thing using Docker build args: https://github.com/algorand/go-algorand-sdk/pull/228

**Comment by michaeldiamant** [comment]
> Currently our Dockerfile runs all cucumber tests in Python 3.7.9:

@jasonpaulos A few notes:
* I updated the mentioned reference in the parent PR: #323.  So, I don't _think_ a change is needed here.
* Thanks for pointing to how go-algorand-sdk matrix tests the integration tests.  I opted to supply a similar approach in https://github.com/algorand/py-algorand-sdk/pull/327.

**Comment by michaeldiamant** [comment]
Merging - I welcome further feedback and will open a new PR should we agree to further changes.

**Pull request merged**
