### PR TITLE
Minor fixes for dependencies, integration test, crypto

### PR DESCRIPTION
**Pull request by pzbitskiy**
1. Use setup.py as source of truth for dependencies
2. Allow ALGORAND_DATA to set data dir in integration test
3. Add encoding.checksum function to incapsulate hashing logic

### CODE REVIEW

**Comment by EvanJRichard** [comment]
LGTM but the travis tests are failing - and, I may be mistaken, but it seems the test failures are unrelated? I'm taking a look now, but I'm not sure.

**Comment by mjiang102628** [comment]
LGTM also; I looked at the error message and it seems like the js sdk is causing the problem (tests start failing on the commit that changes which msgpack package the js sdk is using).

**Comment by pzbitskiy** [comment]
> LGTM also; I looked at the error message and it seems like the js sdk is causing the problem (tests start failing on the commit that changes which msgpack package the js sdk is using).

Right, node js version needs to be 10+ for "for await" expression. Updated but some JS tests still failing.

**Comment by pzbitskiy** [comment]
@rotemh please merge :) Travis CI - Branch does not want to build changes from my fork but for some reason is a prereq for merge.

**Pull request merged**
